name: Build and Publish

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -e .
          uv pip install --system pytest pytest-django

      - name: Run tests
        run: |
          pytest -v

  build-and-publish:
    name: Build and Publish
    needs: test
    runs-on: ubuntu-latest
    # Only publish to PyPI when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Download bootyprint.min.css from latest release
        run: |
          mkdir -p bootyprint/static/bootyprint
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/SvenBroeckling/BootyPrint/releases/latest | jq -r .tag_name)
          curl -s -L https://github.com/SvenBroeckling/BootyPrint/releases/download/${LATEST_RELEASE}/bootyprint.min.css -o bootyprint/static/bootyprint/bootyprint.min.css
          echo "Downloaded bootyprint.min.css from release ${LATEST_RELEASE}"

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
